### ISSUE TITLE
Problem with Dolphin Launcher

### ISSUE THREAD

**Issue by sulaimangari** [magneticchen/Daijishou#193]
Everytime I start dolphin it return this error
![Screenshot_20230124_144448_Daijish](https://user-images.githubusercontent.com/48677109/214237649-023bfe76-38a8-4567-822e-410fabe7621e.jpg)
It looks like daijishou keep executed wrong launcher command by default.
FYI this is fresh install. I already test this on Daijisho released from December until newest released.

**Comment by sulaimangari** [comment]
This happen to Dolphin from play store.

**Comment by timothy-reyes** [comment]
Curious if there is any update on this issue. Myself and many others are having the same problem. 
Happy to work with the developer if their hardware is unable to reproduce the behavior. 

I'm also using the play store version of Dolphin which runs without issue when accessed directly, but fails to load using Daijishou with the error shown in this ticket.

**Comment by magneticchen** [comment]
Did anyone here use other frontends that doesn't have to issue?

**Comment by magneticchen** [comment]
I've tried dolphin on latest dev build and it works for me on Android 13.

**Comment by timothy-reyes** [comment]
I haven't tried other front ends, no. Here is the full log entry though if it helps. 

android.content.ActivityNotFoundException: Unable to find explicit activity class {org.dolphinemu.dolphinemu/org.dolphinemu.dolphinemu.ui.main.MainActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2171)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1145)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1116)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:441)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playIt(DaijishouLibraryModel.kt:576)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem$lambda$13$lambda$12$playItWithRules(DaijishouLibraryModel.kt:628)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$playPlayableItem(DaijishouLibraryModel.kt:698)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play(DaijishouLibraryModel.kt:714)
	at com.magneticchen.daijishou.view_models.DaijishouLibraryModel.play$default(DaijishouLibraryModel.kt:507)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:427)
	at com.magneticchen.daijishou.nav_fragments.PlatformLibraryGridViewNavFragment$onCreateView$4.invoke(PlatformLibraryGridViewNavFragment.kt:426)
	at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder._init_$lambda$0(DaijishouRecyclerView.kt:226)
	at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder.$r8$lambda$dcH5ow6HzTN0-BP2tsljWiEUDBs(Unknown Source:0)
	at com.magneticchen.daijishou.daijishou_recycler_view.DaijishouRecyclerView$Adapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7892)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30880)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by RuffyDragonGarp** [comment]
It didn't work for me as well, but after a long search I found the solution from someone on reddit.

You have to copy the arguments from another Dolphin player.

-n org.dolphinemu.dolphinemu/.ui.main.MainActivity
  -a android.intent.action.MAIN
  -e AutoStartFile {file.uri}

**Comment by magneticchen** [comment]
The problem should be solved by choosing either `gc - org.dolphinemu.dolphinemu` or `wii - org.dolphinemu.dolphinemu`

**Comment by timothy-reyes** [comment]
@magneticchen YES! It's works now! Thanks so much!!
